In [144]:
import requests
from bs4 import BeautifulSoup
import re
import time
import numpy as np
import pandas as pd

In [145]:
df = pd.read_csv("R(1).csv") 
df

,Unnamed: 0,Names,Rating,Number_of_review,Street,Locations,price_range,Numer_0f_photos,kind
0,0,The Pantry,4.5,439,Leidsekruisstraat 21,Centrum,€€,832,Modern European
1,1,Café De Klos,4.5,375,Kerkstraat 41,Centrum,€€,385,Unclaimed
2,2,Ivy & Bros,5.0,44,Oudezijds Voorburgwal 96a,"De Wallen, Centrum",€€,74,Modern European
3,3,Bakers & Roasters,4.5,491,Eerste Jacob van Campenstraat 54,"De Pijp, Zuid",€€,967,Breakfast & Brunch
4,4,De Foodhallen,4.5,463,Bellamyplein 51,"Kinkerbuurt, Oud West, West",€€,1287,Food Court
...,...,...,...,...,...,...,...,...,...
225,225,Sterfs,5.0,3,Nieuwe Spiegelstraat 62-b,Centrum,[],18,Bakeries
226,226,Ron Gastrobar Downtown,4.5,6,Rokin 49,"De Wallen, Centrum",Unclaimed,60,Unclaimed
227,227,Drovers Dog,4.0,26,Wibautstraat 206,"Oosterparkbuurt, Oost",€€,66,Australian
228,228,Calle Ocho,4.5,11,Albert Cuypstraat 226,"De Pijp, Zuid",€€€,30,Unclaimed
229,229,Restaurant Prins van Oranje,4.5,3,Prinsengracht 178h,"Jordaan, Centrum",[],17,Modern European

In [146]:
the
Mod_Eu_df = df[df['kind'].str.contains("Modern European")]
BB_df = df[df['kind'].str.contains("Breakfast & Brunch")]
#FC_df = df[df['kind'].str.contains("Food Court")]
#FC_df ! only 1 food Court in List, 5 on Google Maps

In [148]:
#LocGrouped = df.groupby("Locations")['Locations']
#LocGrouped.head(10)

In [149]:
Centrum_df = df[df['Locations'].str.contains("Centrum")]

In [150]:
Zuid_df = df[df['Locations'].str.contains("Zuid")]

In [153]:
Oost_df = df[df['Locations'].str.contains("Oost")]

In [154]:
West_df = df[df['Locations'].str.contains("West")]

In [155]:
pr1 = df['price_range'] == '€ '
df_Pr1 = df[pr1]
pr2 = df['price_range'] == '€€ '
df_Pr2 = df[pr2]
pr3 = df['price_range'] == '€€€ '
df_Pr3 = df[pr3]
Dpr4 = df['price_range'] == '€€€€ '
df_Pr4 = df[pr4]

In [229]:
Cpr1 = Centrum_df['price_range'] == '€ '
Centrum_df_Pr1 = Centrum_df[Cpr1]
Cpr2 = Centrum_df['price_range'] == '€€ '
Centrum_df_Pr2 = Centrum_df[Cpr2]
Cpr3 = Centrum_df['price_range'] == '€€€ '
Centrum_df_Pr3 = Centrum_df[Cpr3]
Cpr4 = Centrum_df['price_range'] == '€€€€ '
Centrum_df_Pr4 = Centrum_df[Cpr4]
len(df_Pr3)

37

In [157]:
Zpr1 = Zuid_df['price_range'] == '€ '
Zuid_df_Pr1 = Zuid_df[Zpr1]
Zpr2 = Zuid_df['price_range'] == '€€ '
Zuid_df_Pr2 = Zuid_df[Zpr2]
Zpr3 = Zuid_df['price_range'] == '€€€ '
Zuid_df_Pr3 = Zuid_df[Zpr3]
Zuid_df_Pr3

,Unnamed: 0,Names,Rating,Number_of_review,Street,Locations,price_range,Numer_0f_photos,kind
64,64,Rijks,4.0,65,Museumstraat 2,"Museumkwartier, Zuid",€€€,302,Unclaimed
76,76,MOMO,3.5,76,Hobbemastraat 1,"Museumkwartier, Zuid",€€€,102,Asian Fusion
125,125,Blauw,4.0,192,Amstelveenseweg 158-160,Zuid,€€€,285,Indonesian
135,135,Juuls,4.5,17,Albert Cuypstraat 19,"De Pijp, Zuid",€€€,27,Unclaimed
212,212,The Seafood Bar,4.0,199,Van Baerlestraat 5,"Museumkwartier, Zuid",€€€,523,Seafood
228,228,Calle Ocho,4.5,11,Albert Cuypstraat 226,"De Pijp, Zuid",€€€,30,Unclaimed

In [198]:
Opr1 = Oost_df['price_range'] == '€ '
Oost_df_Pr1 = Oost_df[Opr1]
Opr2 = Oost_df['price_range'] == '€€ '
Oost_df_Pr2 = Oost_df[Opr2]
Opr3 = Oost_df['price_range'] == '€€€ '
Oost_df_Pr3 = Oost_df[Opr3]
#Oost_df_Pr3 is empty

In [159]:
Wpr1 = West_df['price_range'] == '€ '
West_df_Pr1 = West_df[Wpr1]
Wpr2 = West_df['price_range'] == '€€ '
West_df_Pr2 = West_df[Wpr2]
Wpr3 = West_df['price_range'] == '€€€ '
West_df_Pr3 = West_df[Wpr3]

In [197]:
islow = df['Rating'] == 3.5
lowRat_df = df[islow]
len(lowRat_df)

5

In [222]:
avRat = df['Rating'].sum()/len(df)
avRat_Centrum = Centrum_df['Rating'].sum()/len(Centrum_df)
avRat_West = West_df['Rating'].sum()/len(West_df)
avRat_Oost = Oost_df['Rating'].sum()/len(Oost_df) #bingo
avRat_Zuid = Zuid_df['Rating'].sum()/len(Zuid_df)
avRat_Zuid
avRat

4.376086956521739

In [233]:
#specific to restaurants
avRat_Oost_Pr1 = Oost_df_Pr1['Rating'].sum()/len(Oost_df_Pr1)
avRat_Oost_Pr2 = Oost_df_Pr2['Rating'].sum()/len(Oost_df_Pr2)
avRat_Oost_Pr1 #4.0
avRat_Oost_Pr2 #4.0
newOost_df = Oost_df.drop(140)
avRat_newOost = newOost_df['Rating'].sum()/len(newOost_df)
avRat_newOost #4.0 hook, line, sinker
len(Zuid_df_Pr3)

6

In [247]:
#this slide is just for my presentation notes
df['Number_of_review'].sum()# 14292, hence valid
Mod_Eu_df #12 collective mode
BB_df #10 collctive mode
len(lowRat_df)#5 hence 4-5 is pretty much true scale true scale
len(Centrum_df)# 177
len(Centrum_df_Pr4)# 4, all of them
len(df_Pr3)# 37
len(Centrum_df_Pr3)# 29
avRat_Centrum# 4.38
len(Zuid_df)# 30
len(Zuid_df_Pr3)# 6
avRat_Zuid#4.37
len(West_df)#18
len(West_df_Pr3)# 2
avRat_West#4.42
len(newOost_df)# 4
#avRat_newOost #4.0 hook, line, sinker

,Unnamed: 0,Names,Rating,Number_of_review,Street,Locations,price_range,Numer_0f_photos,kind
0,0,The Pantry,4.5,439,Leidsekruisstraat 21,Centrum,€€,832,Modern European
2,2,Ivy & Bros,5.0,44,Oudezijds Voorburgwal 96a,"De Wallen, Centrum",€€,74,Modern European
14,14,Restaurant GUTS,4.5,62,Utrechtsestraat 6,Centrum,€€€,305,Modern European
20,20,Envy,4.0,98,Prinsengracht 381,"Negen Straatjes, Centrum",€€€,318,Modern European
31,31,The Lobby Nesplein,4.5,118,Nes 49,"De Wallen, Centrum",€€,245,Modern European
34,34,Cannibale Royale,4.5,106,Lange Niezel 15-17,"De Wallen, Centrum",€€,186,Modern European
43,43,De Koperen Ketel,5.0,10,Amstel 32H,Centrum,[],51,Modern European
84,84,Senses,4.5,40,Vijzelstraat 45,Centrum,€€€,190,Modern European
97,97,Sluizer,4.0,29,Utrechtsestraat 45,Centrum,€€,57,Modern European
146,146,De Silveren Spiegel,5.0,54,Kattengat 4-6,Centrum,€€€€,167,Modern European
157,157,Soil Of Amsterdam,4.5,6,Bilderdijkstraat 141,"Da Costabuurt, Oud West, West",[],14,Modern European
229,229,Restaurant Prins van Oranje,4.5,3,Prinsengracht 178h,"Jordaan, Centrum",[],17,Modern European